In [18]:
import sympy as sp
sp.init_printing(use_unicode=False, wrap_line=False, no_global=True)
import matplotlib.pyplot as plt
from IPython.display import display,Latex
import numpy as np

# Занятие 16
# Алгебра

### Задание 1.

Написать функцию, составляющую матрицу линейного оператора поворота на x градусов или радиан ПО или Против часовой стрелки на плоскости. Параметры: обязательные - угол поворота, необязательные - тип меры угла (градусы или радианы), направление поворота (ПО или Против часовой стрелки). Значения по умолчанию - против часовой стрелки в радианах.

Использовать полученную функцию для выведения на экран координат вектора, полученного поворотом введенного пользователем вектора на заданный пользователем угол.

In [19]:
def lin_oper(alpha, vector, isGrad = False, direction = False):
    if (isGrad): alpha = alpha * sp.pi / 180
    if not(direction):
        A = sp.Matrix([[sp.cos(alpha), -sp.sin(alpha)], [sp.sin(alpha), sp.cos(alpha)]])
        y = A * vector
    else:
        A = sp.Matrix([[sp.cos(alpha), sp.sin(alpha)], [-sp.sin(alpha), sp.cos(alpha)]])
        y = A * vector
    display(y)
    
    
angle = 30
v = sp.Matrix([1,1])
lin_oper(angle, v, isGrad = True, direction = True)

[       ___ ]
[ 1   \/ 3  ]
[ - + ----- ]
[ 2     2   ]
[           ]
[        ___]
[  1   \/ 3 ]
[- - + -----]
[  2     2  ]

### Задание 2.

Найти собственные числа и собственные векторы линейного оператора, заданного матрицей 
$$
\left(\begin{matrix}
-34&20&-5\\
-40&56&-20\\
20&-8&50
\end{matrix}\right)
$$
Воспользоваться eigenvals и eigenvects, проверить выполнение равенства нулю характеристического многочлена $|A-\lambda E|$ и условия $Ax=\lambda x$.


In [20]:
A = sp.Matrix([[-34, 20, -5], [-40, 56, -20], [20, -8, 50]])
#Собственные векторы и числа
res = A.eigenvects()
display(res, A.eigenvals())
P = res[0][2][0].row_join(res[1][2][0]).row_join(res[2][2][0])
display(P)
#Проверка
print('Проверка')
#Собственные числа
lam = sp.symbols('lamda')
lambdas = sp.solve((A - lam * sp.eye(3)).det())
display(lambdas)
#Собственные векторы
evects = []
zero_vect = sp.Matrix((0, 0, 0))
k1, k2, k3, k4 = sp.symbols('k1:5')
display((A - lam * sp.eye(3)).row_join(zero_vect))
for lam in lambdas:
    evects += list(sp.linsolve((A - lam * sp.eye(3)).row_join(zero_vect), k1, k2, k3))
display(evects)
evects = [p.subs(list(evects[0][2].free_symbols)[0], 1) for p in evects]
display(sp.Matrix(evects).transpose())

           [-9/2]             [5/6 ]             [-1/2]   
           [    ]             [    ]             [    ]   
[(-24, 1, [[ -2 ]]), (40, 1, [[10/3]]), (56, 1, [[ -2 ]])]
           [    ]             [    ]             [    ]   
           [ 1  ]             [ 1  ]             [ 1  ]   

[-9/2  5/6   -1/2]
[                ]
[ -2   10/3   -2 ]
[                ]
[ 1     1     1  ]

Проверка


[-lamda - 34      20          -5      0]
[                                      ]
[    -40      56 - lamda     -20      0]
[                                      ]
[    20           -8      50 - lamda  0]

[-9/2  5/6   -1/2]
[                ]
[ -2   10/3   -2 ]
[                ]
[ 1     1     1  ]

### Задание 3.
Построить матрицу оператора из задания 2 в базисе из векторов $(1,1,1)$, $(0,5,3)$ и $(1,6,0)$.


In [21]:
P = sp.Matrix([[1, 0, 1], [1, 5, 6], [1, 3, 0]])
display(P)
newA = P**(-1) * A * P
display(newA)

[1  0  1]
[       ]
[1  5  6]
[       ]
[1  3  0]

[-1   71  26 ]
[            ]
[21   13  -18]
[            ]
[-18  14  60 ]

### Задание 4.

Построить матрицу оператора из задания 2 в базисе из собственных векторов с помощью eigenvects и матрицы перехода. Сравнить диагональные элементы с собственными числами.

In [22]:
#Собственные векторы
res = A.eigenvects()
display(res)
#Матрица перехода
P = res[0][2][0].row_join(res[1][2][0]).row_join(res[2][2][0])
display(P)
#Матрица оператора в базисе из собственных векторов
newA = P**(-1) * A * P
display(newA, A.eigenvals())

           [-9/2]             [5/6 ]             [-1/2]   
           [    ]             [    ]             [    ]   
[(-24, 1, [[ -2 ]]), (40, 1, [[10/3]]), (56, 1, [[ -2 ]])]
           [    ]             [    ]             [    ]   
           [ 1  ]             [ 1  ]             [ 1  ]   

[-9/2  5/6   -1/2]
[                ]
[ -2   10/3   -2 ]
[                ]
[ 1     1     1  ]

[-24  0   0 ]
[           ]
[ 0   40  0 ]
[           ]
[ 0   0   56]

###  Индивидуальное задание

Найти собственные числа и собственные векторы линейного оператора. Построить матрицу оператора в заданном базисе. Построить матрицу оператора в базисе из собственных векторов.

### Теория

http://math.tusur.ru/metod/pr/met1.pdf

http://mathhelpplanet.com/static.php?p=linyeinye-i-kvadratichnye-formy

http://wwwcdl.bmstu.ru/fn1/LinAlg.pdf


In [23]:
A = sp.Matrix([[209, -62, -59], [31, 110, -37], [25, -46, 77]])

#Собственные векторы и числа
res = A.eigenvects()
values = A.eigenvals()
display(res, A.eigenvals())
P = res[0][2][0].row_join(res[1][2][0]).row_join(res[2][2][0])
display(P)
P2 = sp.Matrix([[2, -1, 0], [3, 1, 2], [5, 3, 1]])
newA2 = P2**(-1) * A * P2
display(newA2)
newA = P**(-1) * A * P
display(newA)

          [7/11]              [-1]              [17]   
          [    ]              [  ]              [  ]   
[(72, 1, [[5/11]]), (144, 1, [[-2]]), (180, 1, [[7 ]])]
          [    ]              [  ]              [  ]   
          [ 1  ]              [1 ]              [1 ]   

[7/11  -1  17]
[            ]
[5/11  -2  7 ]
[            ]
[ 1    1   1 ]

[ 72   -1888   -1128 ]
[ --   ------  ------]
[ 17     17      17  ]
[                    ]
[1215   3840    855  ]
[----   ----    ---  ]
[ 17     17      17  ]
[                    ]
[1044   640     2820 ]
[----   ---     ---- ]
[ 17     17      17  ]

[72   0    0 ]
[            ]
[0   144   0 ]
[            ]
[0    0   180]